import 'database_helper.dart';
import 'dart:convert';

class MockData {
  final DatabaseHelper _dbHelper = DatabaseHelper();

  Future<void> createMockUserData() async {
    await _createUser1();
    await _createUser2();
    await _createUser3();
    await _createUser4();
  }

  Future<void> _createUser1() async {
    Map<String, dynamic> user1 = {
      'username': 'HoneyB',
      'email': 'honeyb@gmail.com',
      'password': '123456',
    };
    int userId1 = await _dbHelper.insertUser(user1);
    await _createEntriesForUser1(userId1);
  }

  Future<void> _createEntriesForUser1(int userId) async {
    List<Map<String, dynamic>> entries = [
      {
        'user_id': userId,
        'date': '2024-10-01',
        'time': '08:30',
        'mood': 'great',
        'activity': 'Exercise',
        'note': 'เช้านี้อากาศดี วิ่งในสวนสาธารณะสดชื่นมาก!',
        'image_path': 'assets/park_1.jpg',
        'reactions': jsonEncode({'love': 8, 'like': 3, 'wow': 2}),
        'is_public': 0,
        'is_anonymous': 0,
      },
      {
        'user_id': userId,
        'date': '2024-10-02',
        'time': '12:45',
        'mood': 'good',
        'activity': 'Food',
        'note': 'กินข้าวกลางวันกับเพื่อนๆ สนุกมาก',
        'image_path': 'assets/Pork BBQ party with my classmates.jpg',
        'reactions': jsonEncode({
          "❤️": 15,
          "😊": 7,
          "😢": 0,
          "😮": 0,
        }),
        'is_public': 1,
        'is_anonymous': 0,
      },
      {
        'user_id': userId,
        'date': '2024-10-03',
        'time': '15:00',
        'mood': 'meh',
        'activity': 'Work',
        'note': 'งานเยอะมาก ทำไม่ทันแล้ว',
        'image_path': null,
        'reactions': jsonEncode({'sad': 6, 'like': 2}),
        'is_public': 0,
        'is_anonymous': 0,
      },
      {
        'user_id': userId,
        'date': '2024-10-04',
        'time': '18:00',
        'mood': 'bad',
        'activity': 'Shopping',
        'note': 'ออกไปซื้อของ แต่รถติดมากๆ เหนื่อยเลย',
        'image_path': 'assets/TrafficJam.jpg',
        'reactions': jsonEncode({'sad': 8, 'wow': 1}),
        'is_public': 0,
        'is_anonymous': 0,
      },
      {
        'user_id': userId,
        'date': '2024-10-05',
        'time': '21:15',
        'mood': 'awful',
        'activity': 'Movie',
        'note': 'ดูหนังเรื่องใหม่ ไม่สนุกอย่างที่คิด',
        'image_path': 'assets/Theater.jpg',
        'reactions': jsonEncode({
          "❤️": 0,
          "😊": 0,
          "😢": 7,
          "😮": 2,
        }),
        'is_public': 1,
        'is_anonymous': 0,
      },
      {
        'user_id': userId,
        'date': '2024-10-06',
        'time': '09:00',
        'mood': 'good',
        'activity': 'Travel',
        'note': 'ไปเที่ยวน้ำตกกับครอบครัว อากาศดี',
        'image_path': 'assets/waterfall_1.jpg',
        'reactions': jsonEncode({'love': 6, 'like': 3}),
        'is_public': 0,
        'is_anonymous': 0,
      },
      {
        'user_id': userId,
        'date': '2024-10-07',
        'time': '17:30',
        'mood': 'meh',
        'activity': 'Health',
        'note': 'ตรวจสุขภาพประจำปี รอคิวนานมาก',
        'image_path': null,
        'reactions': jsonEncode({'sad': 5, 'like': 2}),
        'is_public': 0,
        'is_anonymous': 0,
      },
      {
        'user_id': userId,
        'date': '2024-10-08',
        'time': '11:00',
        'mood': 'great',
        'activity': 'Read',
        'note': 'อ่านหนังสือที่ชอบจบไปอีกเล่ม รู้สึกดี',
        'image_path': 'assets/book.jpg',
        'reactions': jsonEncode({
          "❤️": 7,
          "😊": 3,
          "😢": 0,
          "😮": 0,
        }),
        'is_public': 1,
        'is_anonymous': 0,
      },
      {
        'user_id': userId,
        'date': '2024-10-09',
        'time': '19:00',
        'mood': 'good',
        'activity': 'Music',
        'note': 'ฟังเพลงผ่อนคลายตอนเย็น สบายใจ',
        'image_path': null,
        'reactions': jsonEncode({'love': 6, 'like': 4}),
        'is_public': 0,
        'is_anonymous': 0,
      },
      {
        'user_id': userId,
        'date': '2024-10-10',
        'time': '14:00',
        'mood': 'bad',
        'activity': 'Gaming',
        'note': 'เล่นเกมแพ้หลายรอบ หงุดหงิด',
        'image_path': null,
        'reactions': jsonEncode({'sad': 7, 'like': 2}),
        'is_public': 0,
        'is_anonymous': 0,
      },
      {
        'user_id': userId,
        'date': '2024-10-11',
        'time': '10:30',
        'mood': 'meh',
        'activity': 'Socialize',
        'note': 'ไปงานรวมเพื่อน แต่ไม่ค่อยสนุก',
        'image_path': null,
        'reactions': jsonEncode({'sad': 4, 'like': 2}),
        'is_public': 0,
        'is_anonymous': 0,
      },
      {
        'user_id': userId,
        'date': '2024-10-12',
        'time': '08:00',
        'mood': 'great',
        'activity': 'Relax',
        'note': 'วันนี้นอนหลับเต็มอิ่ม ตื่นมาสดชื่น',
        'image_path': null,
        'reactions': jsonEncode({'love': 9, 'like': 4}),
        'is_public': 0,
        'is_anonymous': 0,
      },
      {
        'user_id': userId,
        'date': '2024-10-13',
        'time': '16:00',
        'mood': 'awful',
        'activity': 'Exercise',
        'note': 'ออกกำลังกายแล้วรู้สึกเหนื่อยเกินไป เกือบเป็นลมระหว่างวิ่งบนลู่เลย',
        'image_path': 'assets/gym.jpg',
        'reactions': jsonEncode({
          "❤️": 3,
          "😊": 6,
          "😢": 9,
          "😮": 3,
        }),
        'is_public': 1,
        'is_anonymous': 0,
      },
      {
        'user_id': userId,
        'date': '2024-10-14',
        'time': '09:30',
        'mood': 'good',
        'activity': 'Shopping',
        'note': 'ได้ของที่อยากได้ในราคาลดพิเศษ ดีใจมาก',
        'image_path': null,
        'reactions': jsonEncode({'love': 6, 'like': 5}),
        'is_public': 0,
        'is_anonymous': 0,
      },
      {
        'user_id': userId,
        'date': '2024-10-15',
        'time': '18:45',
        'mood': 'bad',
        'activity': 'Movie',
        'note': 'หนังไม่สนุกเลย เสียดายค่าตั๋ว',
        'image_path': null,
        'reactions': jsonEncode({'sad': 8, 'wow': 1}),
        'is_public': 0,
        'is_anonymous': 0,
      },
      {
        'user_id': userId,
        'date': '2024-10-16',
        'time': '11:15',
        'mood': 'meh',
        'activity': 'Work',
        'note': 'ประชุมยาวไปถึงเที่ยง เหนื่อยสุดๆ',
        'image_path': null,
        'reactions': jsonEncode({'sad': 5, 'like': 2}),
        'is_public': 0,
        'is_anonymous': 0,
      },
      {
        'user_id': userId,
        'date': '2024-10-17',
        'time': '08:30',
        'mood': 'great',
        'activity': 'Travel',
        'note': 'มาส่งน้องชายไปสิงคโปร์สามวันสองคืนที่สนามบิน เขาตื่นเต้นมากๆเลย ฉันก็ด้วยแหละ!!!',
        'image_path': 'assets/Take my younger brother to the airport.JPG',
        'reactions': jsonEncode({
          "❤️": 17,
          "😊": 4,
          "😢": 0,
          "😮": 5,
        }),
        'is_public': 1,
        'is_anonymous': 0,
      },
      {
        'user_id': userId,
        'date': '2024-10-18',
        'time': '13:30',
        'mood': 'awful',
        'activity': 'Health',
        'note': 'ไปหาหมอ ไม่ค่อยสบายเลย',
        'image_path': null,
        'reactions': jsonEncode({'sad': 9, 'wow': 1}),
        'is_public': 0,
        'is_anonymous': 0,
      },
      {
        'user_id': userId,
        'date': '2024-10-19',
        'time': '19:00',
        'mood': 'good',
        'activity': 'Music',
        'note': 'เจอเพลงใหม่เพราะมาก ฟังเพลินเลย',
        'image_path': null,
        'reactions': jsonEncode({'love': 6, 'like': 3}),
        'is_public': 0,
        'is_anonymous': 0,
      },
      {
        'user_id': userId,
        'date': '2024-10-20',
        'time': '14:30',
        'mood': 'meh',
        'activity': 'Gaming',
        'note': 'เกมนี้เริ่มยากขึ้น เล่นยังไงก็ไม่ผ่าน',
        'image_path': null,
        'reactions': jsonEncode({'sad': 4, 'like': 3}),
        'is_public': 0,
        'is_anonymous': 0,
      },
      {
        'user_id': userId,
        'date': '2024-10-21',
        'time': '09:00',
        'mood': 'great',
        'activity': 'Exercise',
        'note': 'วิ่งเช้านี้รู้สึกสดชื่นมาก',
        'image_path': 'assets/park_2.jpg',
        'reactions': jsonEncode({'love': 8, 'like': 2}),
        'is_public': 0,
        'is_anonymous': 0,
      },
      {
        'user_id': userId,
        'date': '2024-10-22',
        'time': '16:45',
        'mood': 'good',
        'activity': 'Socialize',
        'note': 'ไปรวมกลุ่มกับเพื่อนๆ สนุกดี',
        'image_path': 'assets/MeetFriends.JPG',
        'reactions': jsonEncode({
          "❤️": 15,
          "😊": 3,
          "😢": 0,
          "😮": 0,
        }),
        'is_public': 1,
        'is_anonymous': 0,
      },
      {
        'user_id': userId,
        'date': '2024-10-23',
        'time': '18:00',
        'mood': 'bad',
        'activity': 'Movie',
        'note': 'หนังไม่ค่อยสนุก น่าจะเลือกเรื่องอื่น',
        'image_path': 'assets/Theater.jpg',
        'reactions': jsonEncode({'sad': 6, 'wow': 2}),
        'is_public': 0,
        'is_anonymous': 0,
      },
      {
        'user_id': userId,
        'date': '2024-10-24',
        'time': '20:15',
        'mood': 'awful',
        'activity': 'Work',
        'note': 'วันนี้งานยุ่งมาก เหนื่อยทั้งวัน',
        'image_path': null,
        'reactions': jsonEncode({'sad': 9, 'wow': 1}),
        'is_public': 0,
        'is_anonymous': 0,
      },
      {
        'user_id': userId,
        'date': '2024-10-25',
        'time': '07:45',
        'mood': 'great',
        'activity': 'Relax',
        'note': 'เช้านี้ได้พักผ่อนเต็มที่ รู้สึกดีมาก',
        'image_path': null,
        'reactions': jsonEncode({'love': 9, 'like': 4}),
        'is_public': 0,
        'is_anonymous': 0,
      },
      {
        'user_id': userId,
        'date': '2024-10-26',
        'time': '10:30',
        'mood': 'meh',
        'activity': 'Health',
        'note': 'ไปตรวจสุขภาพประจำปี ผลโอเค',
        'image_path': null,
        'reactions': jsonEncode({'like': 4, 'wow': 2}),
        'is_public': 0,
        'is_anonymous': 0,
      },
      {
        'user_id': userId,
        'date': '2024-10-27',
        'time': '09:30',
        'mood': 'good',
        'activity': 'Read',
        'note': 'เจอหนังสือที่น่าสนใจ อ่านเพลิน',
        'image_path': null,
        'reactions': jsonEncode({'love': 6, 'like': 3}),
        'is_public': 0,
        'is_anonymous': 0,
      },
      {
        'user_id': userId,
        'date': '2024-10-28',
        'time': '14:00',
        'mood': 'bad',
        'activity': 'Exercise',
        'note': 'วันนี้เหนื่อยเกินไป วิ่งได้ไม่กี่รอบ',
        'image_path': 'assets/forest_1.jpg',
        'reactions': jsonEncode({'sad': 5, 'like': 1}),
        'is_public': 0,
        'is_anonymous': 0,
      },
      {
        'user_id': userId,
        'date': '2024-10-29',
        'time': '19:00',
        'mood': 'great',
        'activity': 'Movie',
        'note': 'ดูหนังที่ชอบสุดๆ สนุกมาก',
        'image_path': null,
        'reactions': jsonEncode({'love': 7, 'like': 2}),
        'is_public': 0,
        'is_anonymous': 0,
      },
      {
        'user_id': userId,
        'date': '2024-10-30',
        'time': '15:30',
        'mood': 'good',
        'activity': 'Music',
        'note': 'ฟังเพลงโปรด ทั้งวันสดชื่น',
        'image_path': 'assets/lake_1.jpg',
        'reactions': jsonEncode({'love': 5, 'like': 4}),
        'is_public': 0,
        'is_anonymous': 0,
      },
      {
        'user_id': userId,
        'date': '2024-10-31',
        'time': '22:00',
        'mood': 'meh',
        'activity': 'Relax',
        'note': 'ก่อนนอน คืนนี้น่าจะหลับสบาย',
        'image_path': 'assets/forest_1.jpg',
        'reactions': jsonEncode({'like': 3, 'wow': 2}),
        'is_public': 0,
        'is_anonymous': 0,
      }
    ];

    for (var entry in entries) {
      await _dbHelper.insertEntry(entry);
    }
  }


  Future<void> _createUser2() async {
    Map<String, dynamic> user2 = {
      'username': 'SarahLLLL',
      'email': 'sarahlee@gmail.com',
      'password': 'abcdef',
    };
    int userId2 = await _dbHelper.insertUser(user2);
    await _createEntriesForUser2(userId2);
  }

  Future<void> _createEntriesForUser2(int userId) async {
    final List<Map<String, dynamic>> entries = [
      {
        'user_id': userId,
        'date': '2024-10-01',
        'time': '08:00',
        'mood': 'good',
        'activity': 'Exercise',
        'note': 'เช้านี้ได้ออกไปวิ่ง รู้สึกดีมาก',
        'image_path': 'assets/forest_1.jpg',
        'is_public': 0,
        'is_anonymous': 0,
        'reactions': jsonEncode({'like': 3, 'love': 2}),
      },
      {
        'user_id': userId,
        'date': '2024-10-02',
        'time': '14:00',
        'mood': 'meh',
        'activity': 'Work',
        'note': 'งานเยอะมาก รู้สึกเบื่อ',
        'image_path': 'assets/forest_1.jpg',
        'is_public': 0,
        'is_anonymous': 0,
        'reactions': jsonEncode({'sad': 4, 'like': 1}),
      },
      {
        'user_id': userId,
        'date': '2024-10-03',
        'time': '19:30',
        'mood': 'great',
        'activity': 'Movie',
        'note': 'ดูหนังกับเพื่อนๆ สนุกมาก',
        'image_path': 'assets/forest_1.jpg',
        'is_public': 0,
        'is_anonymous': 0,
        'reactions': jsonEncode({'love': 5, 'like': 3}),
      },
      {
        'user_id': userId,
        'date': '2024-10-04',
        'time': '09:00',
        'mood': 'bad',
        'activity': 'Health',
        'note': 'ไม่สบายเล็กน้อย ไปหาหมอมา',
        'image_path': 'assets/forest_1.jpg',
        'is_public': 0,
        'is_anonymous': 0,
        'reactions': jsonEncode({'sad': 6}),
      },
      {
        'user_id': userId,
        'date': '2024-10-05',
        'time': '12:30',
        'mood': 'good',
        'activity': 'Shopping',
        'note': 'ได้ของที่อยากได้ แฮปปี้สุดๆ',
        'image_path': 'assets/forest_1.jpg',
        'is_public': 0,
        'is_anonymous': 0,
        'reactions': jsonEncode({'love': 7, 'like': 2}),
      },
      {
        'user_id': userId,
        'date': '2024-10-06',
        'time': '10:15',
        'mood': 'meh',
        'activity': 'Read',
        'note': 'อ่านหนังสือเล่มใหม่ แต่เนื้อหาไม่ค่อยสนุก',
        'image_path': 'assets/forest_1.jpg',
        'is_public': 0,
        'is_anonymous': 0,
        'reactions': jsonEncode({'like': 3}),
      },
      {
        'user_id': userId,
        'date': '2024-10-07',
        'time': '18:45',
        'mood': 'great',
        'activity': 'Socialize',
        'note': 'นานๆทีจะนัดกันมารวมทีมเล่นวอลเลย์บอลได้ เหนื่อยจนพูดไม่ออกเลยเพราะไม่ได้ออกกำลังกายนาน แต่เล่นกับเพื่อนแล้วสนุกจริงๆ',
        'image_path': 'assets/my sports team after the match.jpg',
        'is_public': 0,
        'is_anonymous': 0,
        'reactions': jsonEncode({'love': 8, 'like': 2}),
      },
      {
        'user_id': userId,
        'date': '2024-10-08',
        'time': '15:30',
        'mood': 'awful',
        'activity': 'Health',
        'note': 'ปวดหัวทั้งวัน ไปหาหมออีกครั้ง',
        'image_path': 'assets/forest_1.jpg',
        'is_public': 0,
        'is_anonymous': 0,
        'reactions': jsonEncode({'sad': 8}),
      },
      {
        'user_id': userId,
        'date': '2024-10-09',
        'time': '20:30',
        'mood': 'good',
        'activity': 'Music',
        'note': 'ปัดสนิทกับกีต้าร์หน่อย ไม่ได้เล่นมาตั้งแต่ขึ้นม.ปลาย ตอนนี้ลืมไปหมดแล้ว',
        'image_path': 'assets/Playing guitar in the classroom.JPG',
        'is_public': 1,
        'is_anonymous': 0,
        'reactions': jsonEncode({
          "❤️": 3,
          "😊": 6,
          "😢": 0,
          "😮": 0,
        }),
      },
      {
        'user_id': userId,
        'date': '2024-10-10',
        'time': '07:30',
        'mood': 'meh',
        'activity': 'Exercise',
        'note': 'วันนี้วิ่งได้แค่ครึ่งทาง เพราะรู้สึกเหนื่อย',
        'image_path': 'assets/forest_1.jpg',
        'is_public': 0,
        'is_anonymous': 0,
        'reactions': jsonEncode({'like': 4, 'wow': 1}),
      },
      {
        'user_id': userId,
        'date': '2024-10-11',
        'time': '16:15',
        'mood': 'bad',
        'activity': 'Work',
        'note': 'งานเยอะมาก รู้สึกเหนื่อยล้า',
        'image_path': 'assets/forest_1.jpg',
        'is_public': 0,
        'is_anonymous': 0,
        'reactions': jsonEncode({'sad': 7}),
      },
      {
        'user_id': userId,
        'date': '2024-10-12',
        'time': '12:00',
        'mood': 'great',
        'activity': 'Travel',
        'note': 'ไปเที่ยวทะเลกับครอบครัว สดชื่นสุดๆ',
        'image_path': 'assets/forest_1.jpg',
        'is_public': 0,
        'is_anonymous': 0,
        'reactions': jsonEncode({'love': 8, 'like': 4}),
      },
      {
      'user_id': userId,
      'date': '2024-10-13',
      'time': '09:30',
      'mood': 'good',
      'activity': 'Food',
      'note': 'วันนี้ได้ลองทานร้านใหม่ อร่อยมาก!',
      'image_path': 'assets/forest_1.jpg',
      'is_public': 0,
      'is_anonymous': 0,
      'reactions': jsonEncode({'like': 5, 'love': 4}),
    },
    {
      'user_id': userId,
      'date': '2024-10-14',
      'time': '20:00',
      'mood': 'awful',
      'activity': 'Health',
      'note': 'รู้สึกไม่สบาย ต้องนอนพักยาว',
      'image_path': 'assets/forest_1.jpg',
      'is_public': 0,
      'is_anonymous': 0,
      'reactions': jsonEncode({'sad': 9}),
    },
    {
      'user_id': userId,
      'date': '2024-10-15',
      'time': '11:45',
      'mood': 'meh',
      'activity': 'Shopping',
      'note': 'ไปห้างซื้อของแต่คนเยอะจนไม่สนุก',
      'image_path': 'assets/forest_1.jpg',
      'is_public': 0,
      'is_anonymous': 0,
      'reactions': jsonEncode({'like': 3}),
    },
    {
      'user_id': userId,
      'date': '2024-10-16',
      'time': '17:00',
      'mood': 'great',
      'activity': 'Socialize',
      'note': 'หลับก่อนใครซะงั้น ตื่นมาดูโพสนี้นะเพื่อน!! ฮ่าๆ',
      'image_path': 'assets/Party at my home.JPG',
      'is_public': 1,
      'is_anonymous': 0,
      'reactions': jsonEncode({
          "❤️": 6,
          "😊": 2,
          "😢": 0,
          "😮": 8,
        }),
    },
    {
      'user_id': userId,
      'date': '2024-10-17',
      'time': '14:30',
      'mood': 'bad',
      'activity': 'Work',
      'note': 'มีปัญหาเรื่องงานที่แก้ยากมาก',
      'image_path': 'assets/forest_1.jpg',
      'is_public': 0,
      'is_anonymous': 0,
      'reactions': jsonEncode({'sad': 7}),
    },
    {
      'user_id': userId,
      'date': '2024-10-18',
      'time': '19:00',
      'mood': 'good',
      'activity': 'Movie',
      'note': 'ดูหนังเรื่องใหม่ สนุกกว่าที่คิดไว้มาก',
      'image_path': 'assets/forest_1.jpg',
      'is_public': 0,
      'is_anonymous': 0,
      'reactions': jsonEncode({'love': 5, 'like': 3}),
    },
    {
      'user_id': userId,
      'date': '2024-10-19',
      'time': '07:30',
      'mood': 'meh',
      'activity': 'Exercise',
      'note': 'เช้านี้ออกกำลังกายได้นิดเดียว เหนื่อยง่ายมาก',
      'image_path': 'assets/forest_1.jpg',
      'is_public': 0,
      'is_anonymous': 0,
      'reactions': jsonEncode({'like': 4}),
    },
    {
      'user_id': userId,
      'date': '2024-10-20',
      'time': '15:00',
      'mood': 'great',
      'activity': 'Music',
      'note': 'ฟังเพลงที่ชอบไปเที่ยวพร้อมกัน ฟินสุดๆ',
      'image_path': 'assets/forest_1.jpg',
      'is_public': 0,
      'is_anonymous': 0,
      'reactions': jsonEncode({'like': 4, 'love': 6}),
    },
    {
      'user_id': userId,
      'date': '2024-10-21',
      'time': '12:45',
      'mood': 'good',
      'activity': 'Food',
      'note': 'วันนี้ทานข้าวกับเพื่อน อร่อยมาก',
      'image_path': 'assets/forest_1.jpg',
      'is_public': 0,
      'is_anonymous': 0,
      'reactions': jsonEncode({'like': 5, 'love': 3}),
    },
    {
      'user_id': userId,
      'date': '2024-10-22',
      'time': '08:30',
      'mood': 'bad',
      'activity': 'Work',
      'note': 'ปัญหาใหม่ในงาน รู้สึกเครียดมาก',
      'image_path': null,
      'is_public': 1,
      'is_anonymous': 1,
      'reactions': jsonEncode({
          "❤️": 0,
          "😊": 0,
          "😢": 6,
          "😮": 0,
        }),
    },
    {
      'user_id': userId,
      'date': '2024-10-23',
      'time': '18:00',
      'mood': 'good',
      'activity': 'Shopping',
      'note': 'ซื้อของขวัญให้เพื่อน รู้สึกตื่นเต้น',
      'image_path': 'assets/forest_1.jpg',
      'is_public': 0,
      'is_anonymous': 0,
      'reactions': jsonEncode({'like': 6, 'love': 2}),
    },
    {
      'user_id': userId,
      'date': '2024-10-24',
      'time': '16:30',
      'mood': 'meh',
      'activity': 'Read',
      'note': 'อ่านหนังสือเล่มเก่าๆ รู้สึกเหมือนเดิม',
      'image_path': 'assets/forest_1.jpg',
      'is_public': 0,
      'is_anonymous': 0,
      'reactions': jsonEncode({'like': 3}),
    },
    {
      'user_id': userId,
      'date': '2024-10-25',
      'time': '11:00',
      'mood': 'great',
      'activity': 'Travel',
      'note': 'เที่ยววัด รู้สึกสดชื่นเต็มที่',
      'image_path': 'assets/temple_1.JPG',
      'is_public': 1,
      'is_anonymous': 0,
      'reactions': jsonEncode({
          "❤️": 5,
          "😊": 6,
          "😢": 0,
          "😮": 0,
        }),
    },
    {
      'user_id': userId,
      'date': '2024-10-26',
      'time': '13:00',
      'mood': 'awful',
      'activity': 'Health',
      'note': 'รู้สึกไม่สบาย ปวดหัวมากๆ',
      'image_path': 'assets/forest_1.jpg',
      'is_public': 0,
      'is_anonymous': 0,
      'reactions': jsonEncode({'sad': 9}),
    },
    {
      'user_id': userId,
      'date': '2024-10-27',
      'time': '21:00',
      'mood': 'good',
      'activity': 'Movie',
      'note': 'ดูหนังที่บ้าน สบายๆ',
      'image_path': 'assets/forest_1.jpg',
      'is_public': 0,
      'is_anonymous': 0,
      'reactions': jsonEncode({'like': 4}),
    },
    {
      'user_id': userId,
      'date': '2024-10-28',
      'time': '19:45',
      'mood': 'meh',
      'activity': 'Exercise',
      'note': 'วันนี้ออกกำลังกายไม่เต็มที่ แต่ยังดีอยู่',
      'image_path': 'assets/forest_1.jpg',
      'is_public': 0,
      'is_anonymous': 0,
      'reactions': jsonEncode({'like': 3, 'wow': 2}),
    },
    {
      'user_id': userId,
      'date': '2024-10-29',
      'time': '14:30',
      'mood': 'bad',
      'activity': 'Work',
      'note': 'งานเยอะมาก ไม่มีเวลาพัก',
      'image_path': 'assets/forest_1.jpg',
      'is_public': 0,
      'is_anonymous': 0,
      'reactions': jsonEncode({'sad': 8}),
    },
    {
      'user_id': userId,
      'date': '2024-10-30',
      'time': '20:15',
      'mood': 'great',
      'activity': 'Socialize',
      'note': 'ได้พบเพื่อนเก่าอีกครั้ง ดีใจมาก',
      'image_path': 'assets/forest_1.jpg',
      'is_public': 0,
      'is_anonymous': 0,
      'reactions': jsonEncode({'love': 7, 'like': 3}),
    },
    {
      'user_id': userId,
      'date': '2024-10-31',
      'time': '23:00',
      'mood': 'great',
      'activity': 'Music',
      'note': 'ปิดท้ายเดือนด้วยดนตรีที่ชอบ',
      'image_path': 'assets/forest_1.jpg',
      'is_public': 0,
      'is_anonymous': 0,
      'reactions': jsonEncode({'love': 8, 'like': 4}),
    },
    ];

    for (var entry in entries) {
      await _dbHelper.insertEntry(entry);
    }
  }



  Future<void> _createUser3() async {
    Map<String, dynamic> user3 = {
      'username': 'MikeJohnson89',
      'email': 'mjsn@gmail.com',
      'password': '545454',
    };
    int userId3 = await _dbHelper.insertUser(user3);
    await _createEntriesForUser3(userId3);
  }

  Future<void> _createEntriesForUser3(int userId) async {
    List<Map<String, dynamic>> entries = [
      {
        'user_id': userId,
        'date': '2024-10-02',
        'time': '09:15',
        'mood': 'good',
        'activity': 'Travel',
        'note': 'ออกไปสำรวจป่า รู้สึกสดชื่นและเงียบสงบ',
        'image_path': 'assets/forest_1.jpg',
        'is_public': 1,
        'is_anonymous': 1,
        'reactions': jsonEncode({
          "❤️": 8,
          "😊": 0,
          "😢": 0,
          "😮": 4,
        }),
      },
      {
        'user_id': userId,
        'date': '2024-10-10',
        'time': '20:30',
        'mood': 'great',
        'activity': 'Socialize',
        'note': 'สนุกกับการพบปะเพื่อนๆ ในงานปาร์ตี้เล็กๆ',
        'image_path': 'assets/male student group.JPG',
        'is_public': 1,
        'is_anonymous': 0,
        'reactions': jsonEncode({
          "❤️": 7,
          "😊": 9,
          "😢": 0,
          "😮": 0,
        }),
      },
      {
        'user_id': userId,
        'date': '2024-10-15',
        'time': '18:00',
        'mood': 'meh',
        'activity': 'Exercise',
        'note': 'ออกกำลังกายวันนี้เหนื่อยนิดหน่อย แต่ก็รู้สึกดี',
        'image_path': 'assets/runtrack.jpg',
        'is_public': 1,
        'is_anonymous': 1,
        'reactions': jsonEncode({
          "❤️": 5,
          "😊": 6,
          "😢": 0,
          "😮": 3,
        }),
      },
      {
        'user_id': userId,
        'date': '2024-10-22',
        'time': '14:45',
        'mood': 'bad',
        'activity': 'Health',
        'note': 'รู้สึกไม่สบาย ต้องพักผ่อนและกินยาบ้าง',
        'image_path': 'assets/medic.jpg',
        'is_public': 1,
        'is_anonymous': 1,
        'reactions': jsonEncode({
          "❤️": 0,
          "😊": 0,
          "😢": 6,
          "😮": 0,
        }),
      },
      {
        'user_id': userId,
        'date': '2024-10-28',
        'time': '19:00',
        'mood': 'good',
        'activity': 'Movie',
        'note': 'ดูหนังโปรดกับครอบครัว ช่วงเวลาที่อบอุ่น',
        'image_path': 'assets/sofa.jpg',
        'is_public': 1,
        'is_anonymous': 0,
        'reactions': jsonEncode({
          "❤️": 3,
          "😊": 7,
          "😢": 0,
          "😮": 0,
        }),
      },
    ];

    for (var entry in entries) {
      await _dbHelper.insertEntry(entry);
    }
  }


  Future<void> _createUser4() async {
    Map<String, dynamic> user4 = {
      'username': 'Emma2002Davis',
      'email': 'emmad@gmail.com',
      'password': '898989',
    };
    int userId4 = await _dbHelper.insertUser(user4);
    await _createEntriesForUser4(userId4);
  }

  Future<void> _createEntriesForUser4(int userId) async {
    List<Map<String, dynamic>> entries = [
      {
        'user_id': userId,
        'date': '2024-10-03',
        'time': '10:00',
        'mood': 'good',
        'activity': 'Shopping',
        'note': 'เดินเล่นตลาดที่หัวหิน สินค้าดีๆ เยอะมาก',
        'image_path': 'assets/hua hin market.JPG',
        'is_public': 1,
        'is_anonymous': 0,
        'reactions': jsonEncode({
          "❤️": 3,
          "😊": 6,
          "😢": 0,
          "😮": 0,
        }),
      },
      {
        'user_id': userId,
        'date': '2024-10-08',
        'time': '15:30',
        'mood': 'great',
        'activity': 'Relax',
        'note': 'ไปพักผ่อนที่ชายหาดกับแม่ อากาศดีมาก',
        'image_path': 'assets/my mom at beach.JPG',
        'is_public': 1,
        'is_anonymous': 0,
        'reactions': jsonEncode({
          "❤️": 10,
          "😊": 6,
          "😢": 0,
          "😮": 4,
        }),
      },
      {
        'user_id': userId,
        'date': '2024-10-13',
        'time': '11:00',
        'mood': 'great',
        'activity': 'Travel',
        'note': 'ครั้งแรกที่ดำน้ำ สนุกและตื่นเต้นมากๆ!',
        'image_path': 'assets/Scuba diving.jpg',
        'is_public': 1,
        'is_anonymous': 1,
        'reactions': jsonEncode({
          "❤️": 5,
          "😊": 0,
          "😢": 0,
          "😮": 8,
        }),
      },
      {
        'user_id': userId,
        'date': '2024-10-18',
        'time': '14:00',
        'mood': 'good',
        'activity': 'Socialize',
        'note': 'เปิดเทอมวันแรกในมหาลัย สุดยอดไปเลย เหมือนได้เริ่มต้นอะไรบางอย่าง',
        'image_path': 'assets/Taking a photo with friends at university.JPG',
        'is_public': 1,
        'is_anonymous': 0,
        'reactions': jsonEncode({
          "❤️": 7,
          "😊": 6,
          "😢": 0,
          "😮": 3,
        }),
      },
      {
        'user_id': userId,
        'date': '2024-10-25',
        'time': '16:45',
        'mood': 'meh',
        'activity': 'Health',
        'note': 'อยู่ในโรงพยาบาล ผ่าตัดอีกแล้ววววววว แย่จริงๆ ปีนี้ป่วยบ่อยจัง',
        'image_path': 'assets/InHospitalRoom.jpg',
        'is_public': 1,
        'is_anonymous': 1,
        'reactions': jsonEncode({
          "❤️": 11,
          "😊": 6,
          "😢": 6,
          "😮": 2,
        }),
      },
    ];

    for (var entry in entries) {
      await _dbHelper.insertEntry(entry);
    }
  }
}
